apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-hello-world
spec:
  template:
    spec:
      containers:
        - name: nextjs-hello-world
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
            requests:
              memory: 200Mi
              cpu: 100m