apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-hello-world
spec:
  ingressClassName: "nginx"
  rules:
  - host: prd.nextjs.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-hello-world
            port:
              number: 3000