apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prd
namePrefix: prd-
commonLabels:
  env: prd
patchesStrategicMerge:
- resourcelimits_patch.yaml
- image_patch.yaml
- ingress_patch.yaml
