apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-hello-world
spec:
  template:
    spec:
      containers:
        - name: nextjs-hello-world
          image: ghcr.io/go2engle/nextjs-hello-world:0.0.1
