apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: qa
namePrefix: qa-
commonLabels:
  env: qa
patchesStrategicMerge:
- resourcelimits_patch.yaml
- image_patch.yaml
- ingress_patch.yaml
